- hosts: terraform-ansible
  become: true
  tasks:
    - name: Instalando Python3 e virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
    - name: Instalando Depedências com pip (Django e Django Rest)
      pip: 
        virtualenv: /home/ubuntu/venv
        name:
          - django
          - djangorestframework
    - name: Iniciando projeto
      shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu/'
    - name: Alterando a configuração de hosts
      lineinfile: 
        path: /home/ubuntu/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
    - name: Rodando o servidor
      shell: '. /home/ubuntu/venv/bin/activate; python /home/ubuntu/manage.py runserver 0.0.0.0:8000'